name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.12
        cache: 'bun'
        
    - name: Install dependencies
      run: bun install

    - name: Build Tailwind CSS
      run: bunx tailwindcss -i ./src/css/tailwind.css -o ./dist/output.css

    - name: Build project
      run: bun run build

    - name: Lint
      run: bun run lint
